# 群聊消息查询插件配置示例
# 将此配置添加到你的config.yaml文件中的plugins部分

plugins:
  # 群聊消息查询插件
  room-message-query-plugin:
    enabled: true              # 启用插件
    priority: 50               # 插件优先级
    trigger_keyword: "查询聊天记录"  # 触发查询的关键词
    default_limit: 50          # 默认查询消息条数
    default_hours: 24          # 默认查询最近几小时

# 使用示例：
# 在群聊中发送以下消息触发查询：
#
# 1. "查询聊天记录" - 使用默认配置（最近50条或24小时）
# 2. "查询聊天记录 100" - 查询最近100条消息
# 3. "查询聊天记录 12小时" - 查询最近12小时的消息
# 4. "查询聊天记录 3h" - 查询最近3小时的消息（支持h/hour后缀）
#
# 插件将返回格式化的聊天记录文本，包括：
# - 消息时间
# - 发送者
# - 消息内容
